server:
  port: 9000

spring:
  application:
    name: oauth2server
  datasource:
    url: jdbc:postgresql://localhost:15432/oauth
    username: postgres
    password: a123456789!
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
          format_sql: true
          show_sql: true
          use_sql_comments: true
logging:
  level:
    org:
      hibernate:
        SQL: debug
        type: debug





